In [1]:
import numpy as np

In [2]:
X = np.array([[1,0,1,1],[0,1,0,0], [1,0,1,0]])

In [3]:
X

array([[1, 0, 1, 1],
       [0, 1, 0, 0],
       [1, 0, 1, 0]])

In [6]:
wh = np.round(np.random.random(size=(4,3)), decimals=2)

In [7]:
wh

array([[ 0.1 ,  0.81,  0.3 ],
       [ 0.26,  0.29,  0.2 ],
       [ 0.4 ,  0.69,  0.81],
       [ 0.2 ,  0.37,  0.35]])

In [8]:
bh = np.round(np.random.random(size=(1,3)), decimals=2)

In [9]:
bh

array([[ 0.5 ,  0.24,  0.47]])

In [10]:
hidden_layer_input = np.dot(X, wh) + bh

In [11]:
hidden_layer_input

array([[ 1.2 ,  2.11,  1.93],
       [ 0.76,  0.53,  0.67],
       [ 1.  ,  1.74,  1.58]])

In [15]:
sigmoid = lambda x: np.round(1/(1 + np.exp(-x)), decimals=2)

In [16]:
hiddenlayer_activations = sigmoid(hidden_layer_input)

In [17]:
hiddenlayer_activations

array([[ 0.77,  0.89,  0.87],
       [ 0.68,  0.63,  0.66],
       [ 0.73,  0.85,  0.83]])

In [22]:
wout = np.round(np.random.random(size=(3,1)), decimals=2)
bout = np.round(np.random.random(size=(1,1)), decimals=2)

In [23]:
wout

array([[ 0.55],
       [ 0.78],
       [ 0.18]])

In [24]:
bout

array([[ 0.58]])

In [28]:
output_layer_input = np.dot(hiddenlayer_activations, wout) + bout

In [29]:
output_layer_input

array([[ 1.8543],
       [ 1.5642],
       [ 1.7939]])

In [31]:
output = sigmoid(output_layer_input)
output

array([[ 0.86],
       [ 0.83],
       [ 0.86]])

In [34]:
y = np.array([[1], [1], [0]])
y

array([[1],
       [1],
       [0]])

In [36]:
E = y - output
E

array([[ 0.14],
       [ 0.17],
       [-0.86]])

In [39]:
derivaties_sigmoid = lambda x : x*(1 - x)

In [42]:
slope_output_layer = np.round(derivaties_sigmoid(output), 2)
slope_hidden_layer = np.round(derivaties_sigmoid(hiddenlayer_activations), 2)

In [43]:
slope_hidden_layer

array([[ 0.18,  0.1 ,  0.11],
       [ 0.22,  0.23,  0.22],
       [ 0.2 ,  0.13,  0.14]])

In [44]:
slope_output_layer

array([[ 0.12],
       [ 0.14],
       [ 0.12]])

In [54]:
lr = 1

In [56]:
delta_output = np.round(E * slope_output_layer * lr, 2)
delta_output

array([[ 0.02],
       [ 0.02],
       [-0.1 ]])

In [58]:
error_at_hidden_layer = np.round(np.dot(delta_output, wout.T),2)
error_at_hidden_layer

array([[ 0.01,  0.02,  0.  ],
       [ 0.01,  0.02,  0.  ],
       [-0.06, -0.08, -0.02]])

In [60]:
d_hidden = np.round(error_at_hidden_layer * slope_hidden_layer,2)
d_hidden

array([[ 0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ],
       [-0.01, -0.01, -0.  ]])

In [63]:
wout = np.round(wout + np.dot(hiddenlayer_activations.T, delta_output), 2)
wh = np.round(wh + np.dot(X.T, d_hidden), 2)

In [62]:
wout

array([[ 0.51],
       [ 0.73],
       [ 0.13]])

In [64]:
wh

array([[ 0.09,  0.8 ,  0.3 ],
       [ 0.26,  0.29,  0.2 ],
       [ 0.39,  0.68,  0.81],
       [ 0.2 ,  0.37,  0.35]])

In [76]:
bh = bh + np.sum(d_hidden, axis = 0)
bout = bout + np.sum(delta_output, axis=0)

In [77]:
bh

array([[ 0.49,  0.23,  0.47]])

In [78]:
bout

array([[ 0.52]])